### PR TITLE
Membership Payment Form Redesign

### PR DESCRIPTION
**Pull request by KerimD**
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ClayMav — CHANGES_REQUESTED** [review]
Already have an issue here, in the current web on master, if the person provides no keys, the page loads fine - in this version, without keys, the page crashes. Please fix. I should not need keys to open the page, nor to open the payment form, but only to submit without an issue and that issue should be handled on the front end

**Review by ClayMav — DISMISSED** [review]
Functionality:
- Scrolling is still enabled while the popup is on the screen, which may or may not make sense
- Due to scrolling, text on the hero is on top of the popout, use z-index to fix this
Screen Shot 2020-11-15 at 02 45 36
- using the authentication required card does not actually apply the membership as expected. as seen at [https://stripe.com/docs/testing](https://stripe.com/docs/testing)

Style:
- The hover effect for the button opening the popup is gaudy and obscene, compare to the other page buttons
- We had discussed putting some information about what they were purchasing on the card that pops up, remember, this feature is mainly about making it easier to trust this - we may also want to put a "Powered by Stripe" note on the popout
- review button also needs to get better treatment
- dollar sign after dollars is weird
Screen Shot 2020-11-15 at 02 51 49
- this info seems kind of useless without context, also is this sent to them in email or anything? Any way they can get this if they dont save it now?
Screen Shot 2020-11-15 at 02 52 23

**Review by cjwagn1 — CHANGES_REQUESTED** [review]
Make mobile-friendly:

image

**Review by cjwagn1 — CHANGES_REQUESTED** [review]
Looks good. 

Needs to fix up a bit of squishing on the card number and expiration date. 

Example 1: 
image

Example 2: 
image

Once that and the powered by stripe CDN image is up, then this should be good to go.

**Review by cjwagn1 — APPROVED** [review]
Looks good!

**Pull request merged**
