### PR TITLE
Admin tool for generating redemption codes

### PR DESCRIPTION
**Pull request by ClayMav**
# Pull Request Description

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ClayMav** [comment]
@Andrew-Gibson42 and @henrievjen, can you pull this locally, check if the redemption code creation page works, and then fully test all features on event and membership pages for me? Many things changed in this so I would love some other peoples eyes on this

**Comment by Andrew-Gibson42** [comment]
I noticed a few issues-- I'm not sure if some of these were already the case in the base membership tool or if this changed, but I'm noticing behaviors I didn't before.

Membership tool
--------------------------------
- When you update the expiration date, four antd messages are appearing (update shirt data loading, expiration data loading, update shirt status, expiration date update success). It seems that only the second and fourth messages should appear.
- The expiration date is set to one day before the date picker's date value.
- If you choose a date in the date picker and do not confirm (by clicking off the box) the expiration date correctly doesn't change, but if you click the edit button again, that previously cancelled date is still in the date picker. (This one's not a functional issue, but it's something I remember dealing with a few times during the development of the membership tool, so something must have been shifted.)

Everything seems to be working correctly with the events tool.

**Comment by ClayMav** [comment]
Those antd messages are from the initial design. The expiration date does apply one day behind, and I don't love it, but expiration dates are applied loosely, as in by semester, not by day, so I don't really mind it being off by a day at least for now. It needs to be fixed down the line - I think its on the backend. And once again I am not super worried about the third thing. The membership tool could use some love soon, but for now all of this stuff is acceptable.

**Comment by ClayMav** [comment]
@Andrew-Gibson42 Can you go ahead and submit a review for me

**Pull request merged**
